### ISSUE TITLE
Add items to a list

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#60] opened 2020-09-16 08:51 UTC
## What
The design lets users enter multiple entries of related things, eg previous names. 

### Example: Health assessment prototype

<img width="782" alt="Screen Shot 2021-03-22 at 08 30 49" src="https://user-images.githubusercontent.com/57486301/111961434-f5740800-8ae8-11eb-9511-a0b960358553.png">

### Example: Get your state pension

<img width="702" alt="Screen Shot 2021-03-22 at 08 31 44" src="https://user-images.githubusercontent.com/57486301/111961515-12104000-8ae9-11eb-8f92-450707a36790.png">

## Why
Users may have multiple answers to a question about names, locations, jobs etc, that can be added as a list.

## Anything else

This issue has been looked at by GDS but they have wrapped it in to edit a list issue which is now closed. It could be added to the 'add a thing' issue.
A number of different approaches detailed https://github.com/dwp/design-examples/issues/25

**Original issue information:** 30 July 2018 Chris Armstrong https://github.com/dwp/design-system-community-backlog/issues/19

**Comment by jonhurrell** [comment] 2022-02-15 11:40
Close as duplicate of https://github.com/dwp/design-system-community-backlog/issues/54

**Closed by jonhurrell** 2022-02-15 11:40 UTC
Labels: pattern
