### ISSUE TITLE
Alternative form of contact with citizen needed

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#59] opened 2020-09-15 15:34 UTC
## What
As a user of an internal system I need to clearly see/know the citizen I need to contact will need to be contacted by an alternative way, such as by using large print letters

**Original issue information:** 6 September 2018 by Simon Wilson https://github.com/dwp/design-system-community-backlog/issues/18

**Comment by HelenOsg** [comment] 2021-03-24 12:49
https://github.com/dwp/design-system-community-backlog/issues/16

**Comment by jonhurrell** [comment] 2022-02-15 11:53
Duplicate of https://github.com/dwp/design-system/issues/426

**Closed by jonhurrell** 2022-02-15 11:53 UTC
Labels: pattern
